name: mini
description: "Offline personal/business finance manager for small informal entrepreneurs."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  sqflite: ^2.4.1
  path: ^1.9.0
  provider: ^6.1.2
  intl: ^0.20.2
  bcrypt: ^1.1.3
  sqflite_common_ffi: ^2.3.4+3
  sqflite_common_ffi_web: ^0.4.5+2
  shared_preferences: ^2.3.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true